# Generated by Django 4.2.4 on 2023-09-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
